### ISSUE TITLE
Version update of Boruta on pypi?

### ISSUE THREAD

**Issue by proexcuse** [scikit-learn-contrib/boruta_py#111]
Hello, 
I'd love to use new features like return_df in BorutaPy transform method, but can't with the latest version on pypi.
Is there any chance that I can use soon? When is the next update?

**Comment by bruderooo** [comment]
@danielhomola wdyt?

**Comment by rodrigc** [comment]
I am taking a data science class, and our lectures use Boruta_py.
@danielhomola can you make a new release on PyPi?  The existing version of Boruta on PyPi
does not have this fix: https://github.com/scikit-learn-contrib/boruta_py/pull/102
which is necessary to work with the newest versions of NumPy.

**Comment by rodrigc** [comment]
@danielhomola @erikvdp I think all that is required is to create a new tag in Git.  This will trigger the GitHub Action to push the new release to PyPi.

**Comment by erikvdp** [comment]
I unfortunately have no permissions to push a new tag:

```
git push origin 0.4
remote: Permission to scikit-learn-contrib/boruta_py.git denied to erikvdp.
fatal: unable to access 'https://github.com/scikit-learn-contrib/boruta_py.git/': The requested URL returned error: 403
```

I thnk only @danielhomola has the rights to do so.

**Comment by rodrigc** [comment]
@erikvdp Thanks for trying.  Hopefully @danielhomola can respond

**Comment by xujiboy** [comment]
May I know when will version 0.4 be on pypi?

**Comment by danielhomola** [comment]
I did make a new tag but for some reason the  github workflow (making a new relesae to pypi automatically) does not run.. can anyone help w updating the workflow? Thanks

**Comment by rodrigc** [comment]
@danielhomola I submitted a PR https://github.com/scikit-learn-contrib/boruta_py/pull/132 to allow manually testing
the GitHub Action, in addition to have it automatically run on tag creation.

**Comment by danielhomola** [comment]
thanks, merged it in, let's see if it works!

**Comment by rodrigc** [comment]
@danielhomola the GitHub action failed here: https://github.com/scikit-learn-contrib/boruta_py/actions/runs/10347360514/job/28637478609 .  Did you properly set up the token?

**Comment by rodrigc** [comment]
@danielhomola I submitted another PR https://github.com/scikit-learn-contrib/boruta_py/pull/133
and a request in that PR for you to enable trusted PyPI publishing from GitHub to PyPI.

**Comment by danielhomola** [comment]
thanks @rodrigc, had to debug 2 more things but now it's working :tada:

**Comment by rodrigc** [comment]
@danielhomola Glad to hear it.  I guess configuring the PyPi repo with:
 https://docs.pypi.org/trusted-publishers/adding-a-publisher/
is a new step for publishing from GitHub to PyPi.
