### ISSUE TITLE
n_jobs = -1 does not work

### ISSUE THREAD

**Issue by seralouk** [scikit-learn-contrib/boruta_py#25]
Hello,

I am trying to use all my cores when using boruta_py.
I set for instance, n_jobs=-1 inside randomforest class but only one core does the job.
I get no errors/warnings

**Comment by danielhomola** [comment]
Hi there, 

do can you train a RF with multiple cores in scikit-learn?

**Comment by seralouk** [comment]
Hi,

Yes I can run RF with multiple cores in scikit-learn.

**Comment by danielhomola** [comment]
Can you please provide a reproducible example and your version of scikit learn, scipy and numpy? Thanks!
