### ISSUE TITLE
Results vary in R in Python implementation

### ISSUE THREAD

**Issue by sisupalan** [scikit-learn-contrib/boruta_py#28]
It is mentioned "the two_step parameter has to be set to False, then (with perc=100) BorutaPy behaves exactly as the R version."
Inspite of doing this, results vary significantly. Is there a way to replicate the results exactly as the R version of the package?

**Comment by mbq** [comment]
Boruta, in general, can be unstable when the number of trees in the forest is too low (prohibiting importance scores from convergence) -- you may want to check it out.

**Comment by danielhomola** [comment]
closing this now! as always, thanks a lot Miron for chiming in!
