### ISSUE TITLE
Categorical features

### ISSUE THREAD

**Issue by Taakn** [scikit-learn-contrib/boruta_py#41]
Hello,

More of a question than an issue, but how do you handle categorical features? 

Also seems like y needs to be an int? Otherwise if I leave it as float I am getting an error.

Thanks!

**Comment by SymbolicSquared** [comment]
For categorical features you will need to vectorize/dummy code, just like you would if you plan to use any classifier in sklearn. I suggest pandas get_dummies method.

**Comment by ThomasBury** [comment]
Hi,

regarding categorical:
- large cardinality biases impurity based var.imp --> would it be possible to use permutation imp instead (available in scikit)?
- dummifying is not advised for tree-based models (making the trees unstable and deeper than expected) see https://roamanalytics.com/2016/10/28/are-categorical-variables-getting-lost-in-your-random-forests/. Using lightgbm, you can encode as integer and use the native method to handle cat. pred. Alternative: use https://github.com/scikit-learn-contrib/category_encoders

**Comment by danielhomola** [comment]
Submit a PR with tests and I'll have a look.
