### ISSUE TITLE
Question: Feature Selection for Regression Problems

### ISSUE THREAD

**Issue by SymbolicSquared** [scikit-learn-contrib/boruta_py#45]
The examples provided apply Boruta for feature selection in classification problems. Can Boruta be accurately applied for feature selection in regression problems? If so, what regression estimator would be most appropriate? (i.e. RandomForestRegressor, GradientBoostingRegressor, etc.)

**Comment by Sandy4321** [comment]
yes, it would be great to answer on this question, since your wrote : Compatible with any ensemble method from scikit-learn ?

**Comment by danielhomola** [comment]
RandomForrestRegressor should work fine with Boruta.

**Comment by Sandy4321** [comment]
it is exactly the question: can it be used for Logistic regression from scikit learn or not?
from your answer fallows that not: it works only for RandomForrestRegressor from scikit learn
may you write clear way ; can it be used for Logistic regression from scikit learn???

**Comment by danielhomola** [comment]
It seems like you haven't read the paper or now how boruta works. It might be useful.

**Comment by Sandy4321** [comment]
Boruta conceptually should work with Logistic Regression , only the question is : did you coded this option?

**Comment by danielhomola** [comment]
No.

**Comment by Sandy4321** [comment]
interesting why?

**Comment by danielhomola** [comment]
because it's not what's in Boruta (you might have missed which package you're using) and besides that why would anyone use a linear classifier instead of RF or other ensemble?
