### ISSUE TITLE
donot suport lgb/xgb?

### ISSUE THREAD

**Issue by Jie-Yuan** [scikit-learn-contrib/boruta_py#52]
donot suport lgb/xgb?

**Comment by hatunina** [comment]
I also had the same question.
I solved it by using lgb scikit-learn api .
Because Boruta uses "feature_importances_" internally.

**Comment by marcospiau** [comment]
I managed to get lgb working by following the instructions on the comments section of this kernel on Kaggle (https://www.kaggle.com/ogrellier/noise-analysis-of-porto-seguro-s-features). You need to change the line 282 of boruta_py.py to:
self.estimator.set_params(random_state=self.random_state.get_state()[2])
