### ISSUE TITLE
What to do when Boruta seems to be rejecting more features than it should?

### ISSUE THREAD

**Issue by felipheggaliza** [scikit-learn-contrib/boruta_py#55]
Hi, 

I am trying to play with Boruta and sometimes I see that this algorithm is rejecting more features than it should. What parameters can I tune either in Boruta Algorithm or Random Forest in order to have it working properly?

**Comment by danielhomola** [comment]
> more features than it should
How do you know what it `should` do? Seems like you have strong priors when looking at your data.

> to have it working properly?
Boruta is a published FS method, used by thousands of people in different fields and competitions. It is working properly, as in, it's doing what it says on the tin (have you read the paper?)

None of this is quantitative, benchmarked or helpful in any sense, so I'll recommend you read the paper, or at least the readme (then you'd know, adjusting the p-value cut-off helps).
