### ISSUE TITLE
Iterating over 0-d array

### ISSUE THREAD

**Issue by ADI10HERO** [scikit-learn-contrib/boruta_py#60]
When running boruta if all features get selected the code gives error when _nanrankdata is called under BorutaPy 

![image](https://user-images.githubusercontent.com/39651310/57373549-43fab080-71b6-11e9-9a47-71424cec1e47.png)

**Comment by danielhomola** [comment]
this should be fixed in the new pypi version.. please run 
```
pip uninstall boruta
pip install boruta
```
thanks
