### ISSUE TITLE
How to use boruta_py with BaggingClassifier?

### ISSUE THREAD

**Issue by BlackArbsCEO** [scikit-learn-contrib/boruta_py#75]
Does it work with ensembles besides randomforest?

**Comment by UTUnex** [comment]
Hi, I also met the problem that a-berg mentioned. It seems that the model must explicitly have the parameter 'max_depth' to make it usable in BorutaPy. I'm working with the model 'AdaBoostClassifier' and 'RUSBoostClassifier', both of which do not explicitly have the 'max_depth' in their parameter lists and when either of them is put in BorutaPy, there just appears the KeyError: 'max_depth'. I wonder whether this problem can be solved.

**Comment by danielhomola** [comment]
This is the only place we rely on the `max_depth` param of the estimator
https://github.com/scikit-learn-contrib/boruta_py/blob/master/boruta/boruta_py.py#L398

It'd be trivial to add a try/except statement here, and make sure to inform the user if the estimator does not have a `max_depth` property and as a consequence we cannot automatically estimate the number of trees to use.. Any one of you'd like to submit a PR for this?

Thanks

**Comment by UTUnex** [comment]
@danielhomola ,hi, thank you for your reply. So will you consider making some modification to the code to support those estimators like Adaboost which itself doesn't explicitly have the max_depth parameter but its base_estimator like DecisionTree does have this parameter. So I wonder whether it's possible for you to make the BorutaPy able to extract such implict max_depth in the future.

Besides, I also tried to put the XGBoostClassifier and LightGBMClassifier in BorutaPy and again the error occurred, it's about the RandomState problem : 'TypeError: Unknown type of parameter:random_state, got:RandomState'. I dont know how to solve this, could you please help?
Do you have the plan to improve the compatibility of BorutaPy with other popular tree-based models besides RandomForest?

**Comment by danielhomola** [comment]
?? no.. that's why I asked you to submit a PR.. if you do so, I'll review it and merge it happily but I don't have time to actively do dev on this repo any more.
