### ISSUE TITLE
[ENH] Include importance history in the output

### ISSUE THREAD

**Issue by davidfstein** [scikit-learn-contrib/boruta_py#87]
The R package provides the ImpHistory object in the output of the fit feature selector. This allows for more granular interpretation of the importance of the features beyond accepted, tentative, and rejected. I think it would be worthwhile to include this feature in this package as well.

**Comment by danielhomola** [comment]
Kinda sounds like you're looking for reasons to include badly performing features.. I'd stay away from anything that's not confirmed..

**Comment by davidfstein** [comment]
No not at all. I just want a more granular look at the accepted features. I'm hoping for something like this.
![image](https://user-images.githubusercontent.com/48538937/96762511-67fc8280-13a7-11eb-9cb6-c4d2fef7f26d.png)

I'm working on a biological classification problem and it would be nice to have a look at which features provide the most explanatory value.
